### ISSUE TITLE
Plutus GEM and Rails 4 raising an error

### ISSUE THREAD

**Issue by HermannHH** [mbulat/plutus#30]
I am able to create new Entries using the code found in the documentation when I place this code entirely in it's own method. Whenever I add it into another method (ex. create) I am presented with an error. This error states undefined method `find_by_name' for #<Class:0xb2f23cc8>.

It is really weird as there are absolutely no problems if the exact same code is placed in it's own method.

**Comment by mbulat** [comment]
I can't re-create this issue, and there's not really enough information here to figure out what the problem is. I'm closing this issue for now and will take the discussion to your post in the plutus user group.

**Comment by mbulat** [comment]
Actually, in writing a response to your user group post, it suddenly occurred to me that you you might have another model in your system named Account. If so, that would explain the odd behavior. Re-opening because if that's the case, this could be fixed by making sure the Entry.build function uses the namespaced model names.

A workaround would obviously be to rename your existing Account model

**Comment by HermannHH** [comment]
I do have another model named Account, so you are completely right. How would I go about ensuring that the Entry.build function uses the namespaced name? This sounds a little confusing to me. I can't really think of another logical name for my other model. Thanks for the response by the way and also thanks for the great GEM!

**Comment by mbulat** [comment]
I've just pushed out an update... you should be able to `bundle update plutus` and get version 0.10.1 with a fix. Let me know how it works.

**Comment by HermannHH** [comment]
@mbulat  Thank you very much. This has fixed the issue immediately! I appreciate it. Keep up the good work.
