### ISSUE TITLE
Requiring account.name and entry.description

### ISSUE THREAD

**Issue by rosskevin** [mbulat/plutus#35]
I have multi-tenancy use case where I really don't need the account name, not a big deal, but I'm filling the db with the same symbols for name i.e. `:accounts_receivable`. I looked past this because I'll likely try to i18n present these based on the `name`.

Now, I've just coded my Entries, and upon first run I hit `ActiveRecord::RecordInvalid: Validation failed: Description can't be blank`.  I'm using a `:commercial_document` reference, so a description is insignificant to me, and would simply be adding insignificant string information stuck in the database as far as I can tell for my use case.

Am I missing something?  Would you mind if I submitted a pull for conditional Entry description validation, only requiring presence if there isn't a commercial_document?

**Comment by mbulat** [comment]
Sorry for the delay in getting back on the issues here.. been swamped lately.

So i'm a little hesitant to apply this patch. My concern is that the commercial document description is being forced to potentially do separate things here. For instance the description for invoices in my system are customer friendly descriptions, whereas the descriptions in Plutus are meant for an accountant. For example an invoice description in my system may be different per invoice for a certain type of transaction, but the description in Plutus is the same for all of those transactions, making the accountant's job a little easier. 

So I guess I could toss the presence requirement, but I think there's a good reason to keep it. Mostly because I consider Plutus to be the tamed, accountant friendly set of tables that above all should be consistent. The description presence requirement helps enforce that consistency across entries. I view Plutus as a way to ensure that the craziness and ad-hoc nature of many invoicing/ordering systems doesn't spill over into what an accountant wants to see. The Plutus tables, then, should all be self consistent and follow the principle of least surprise.

**Comment by rosskevin** [comment]
> My concern is that the commercial document description is being forced to potentially do separate things here. For instance the description for invoices in my system are customer friendly descriptions, whereas the descriptions in Plutus are meant for an accountant.

In our system, we won't use the `entry.description`, and if we did, where the data could be dynamically resolved (it lives or could be derived from the commercial document), it is just duplication.  We do require the commercial document as a basis for the entry, so it makes quite a bit of sense to be this way.  

> The description presence requirement helps enforce that consistency across entries.

With that said, the commercial document presence requirement would serve the same purpose.

> I view Plutus as a way to ensure that the craziness and ad-hoc nature of many invoicing/ordering systems doesn't spill over into what an accountant wants to see.

I'm not sure a gem needs to force this pattern of use or opinion.  This gem cannot know how it is being used in a larger system.  When an invoice is `closed` in my system, entries are created (and the invoice becomes un-editable).  I can string together a description then, or yield a dynamic description of `invoice 123` later, one is static and perhaps unnecessarily stored data, the other has zero duplication.

> The Plutus tables, then, should all be self consistent and follow the principle of least surprise.

If it `is a(n)` `Entry` `for a` `CommercialDocument`, why does it not make sense to have a dynamic description based on the commercial document model?  How is a hardcoded/interpolated string that is subject to refactoring make a database table more consistent?  I could then have a mix of `Invoice for a product` and `Product invoice` and `Invoice #123` populating the table depending on which codebase created the entry over time.

Let me close by saying thank you for sharing your work.  I'm quite glad I came across it and plan to continue to use it.  

While it is certainly your prerogative to reject this and #37, doing so pushes me to maintain a fork for what I think are options that could be simply integrated.  In any case, thank you again.
