### ISSUE TITLE
Multi-tenancy configurable attribute name

### ISSUE THREAD

**Issue by rosskevin** [mbulat/plutus#37]
I have a multi-tenancy app with an existing model `Tenant`.  Unfortunately, while it serves the role of identifying tenant in the system, we have an entity `Books` that wraps up state and behavior for financial aspects of the system, which includes our references to Plutus.

I'm going to take a shot at making `tenant` configurable so that I can use `books` instead.  I'll default it to `tenant` though so nothing should change.

Any thoughts are appreciated.

**Comment by rosskevin** [comment]
Enhancement, pull request #39 available.

**Comment by mbulat** [comment]
@rosskevin Just back from vacation and catching up. Will try and look at these in the next couple of days. Thanks!

**Comment by rosskevin** [comment]
FYI - I've been using this with success.  Admittedly, I didn't throw time/attention to older versions of ruby (I'm on 2.2+ with rails 4.2+).

**Comment by mbulat** [comment]
Not sure why this is needed. Isn't it okay to have Plutus.tenant refer to a Book class? I would actually think it's advisable, since the attribute name of "tenant" clearly indicates that it's not a standard relation, but specifically for multi-tenancy purposes.

Also, in general I find it advisable for gems to support several versions of ruby previous to the latest. Although my app may be using Ruby 2.2 and Rails 4.2, unless it's difficult to provide compatibility, I generally assume users of the gem might be a couple versions behind. Most people won't have upgraded to Ruby 2.2 until Rails 5 comes out with it as a requirement. Even then, for a public gem, I wouldn't race to use breaking syntax or features unless it makes a big difference in implementation. Basically it's got to pass all the required Travis Build tests.

**Comment by rosskevin** [comment]
This wasn't _needed_ but was nice to have, and in our system it prevents significant confusion when navigating the model structure.  Referring to `entry.tenant`, when you have a `Tenant` in your system, yet the result is not a `Tenant` is quite confusing.
