### ISSUE TITLE
Entries don't have a proper date associated

### ISSUE THREAD

**Issue by kempchee** [mbulat/plutus#49]
Currently, entries are timestamped, but since entries might be put into the system at a different time from the time at which the underlying economic event took place, these timestamps are probably not very useful.  Would you be in favor of adding a field such as "economic_event_date" to the plutus entry model?

**Comment by mbulat** [comment]
So, previously I've been pushing back against this, since for my use case, the timestamp works fine. However, there have been enough requests for this it should probably be implemented, and I've come to the view that it's cleaner than overloading the timestamp field. 

My inclination would be to keep it simple and just call the field "date".

**Comment by rosskevin** [comment]
@kempchee I've implemented this on my maintained fork using `effective_at`: https://github.com/rosskevin/plutus

Details in the readme "Fork" section, you can also check the commits.

**Comment by mbulat** [comment]
Going to track this under #45 since it's mentioned there with other feature enhancements.
