### ISSUE TITLE
Creating entries for multi-tenant

### ISSUE THREAD

**Issue by inopinatus** [mbulat/plutus#55]
The multi-tenancy support seems not to extend beyond creating an account. In particular the string-based account lookup used for all the examples uses find_by_name! without reference to tenant_id. This could easily lead to the wrong account being selected.

Was this an intentional omission? Surely if multi-tenancy is enabled, it should be explicitly enforced throughout the API? Or was some other mechanism for account selection intended.

**Comment by mbulat** [comment]
The multi-tenancy support is pretty simple at the moment. It's assumed you'll be keeping track of the tenant and specifying the correct accounts manually.

I've created a note and example in the Readme via 5785543b338b8ef7350126cb7b99316bd5f3e393 to outline the issue. Basically you just lookup the account directly, and specify that during the Entry building rather than using the convenience method.  

Perhaps if tenancy is turned on, the convience method could throw a warning or something if we wanted to get fancy.
